In [17]:
import numpy as np

In [18]:
sales=[0, 5, 155, 0, 518, 0, 1827, 616, 317, 325]
sales_array = np.array(sales)
type(sales_array)

numpy.ndarray

In [19]:
print(f'ndim: {sales_array.ndim}')
print(f'shape: {sales_array.shape}')
print(f'size: {sales_array.size}')
print(f'Data Type: {sales_array.dtype}')
sales_array 

ndim: 1
shape: (10,)
size: 10
Data Type: int64


array([   0,    5,  155,    0,  518,    0, 1827,  616,  317,  325])

In [20]:
## array creation
np.ones(5)

array([1., 1., 1., 1., 1.])

In [21]:
np.zeros(20, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
np.zeros(20, 'int').reshape(5,4)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [23]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [ ]:
## random number generate
rng = np.random.default_rng(212)
rng.random(7)

array([0.57255591, 0.29498955, 0.48229339, 0.78641928, 0.17335266,
       0.13988705, 0.99499356])

In [28]:
rng.integers(0,10,50)

array([2, 6, 1, 2, 3, 7, 1, 8, 7, 9, 8, 5, 8, 5, 6, 1, 1, 8, 8, 5, 0, 7,
       1, 3, 2, 9, 7, 3, 0, 3, 2, 4, 8, 2, 7, 1, 5, 1, 4, 7, 9, 1, 7, 3,
       6, 7, 9, 2, 7, 3])

In [29]:
rng.normal(50,5,10)

array([43.10424061, 46.71461488, 42.03925035, 50.93491635, 47.59780066,
       49.72359727, 54.09630912, 55.72008821, 43.38897117, 49.42950296])

In [33]:
## task 2
np_array = np.linspace(10,100,10).reshape(5,2)
np_array

array([[ 10.,  20.],
       [ 30.,  40.],
       [ 50.,  60.],
       [ 70.,  80.],
       [ 90., 100.]])

In [39]:
my_array = np.arange(10,101,10).reshape(5,2)
my_array

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])