In [22]:
import numpy as np
import pandas as pd

In [23]:
## basic series
array = np.arange(5)
array

array([0, 1, 2, 3, 4])

In [24]:
series=pd.Series(array)
series

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [25]:
series.values

array([0, 1, 2, 3, 4])

In [26]:
series.mean()

np.float64(2.0)

In [27]:
series.index = [10,20,30,40,50]

In [28]:
series

10    0
20    1
30    2
40    3
50    4
dtype: int64

In [29]:
## type conversion 
series

10    0
20    1
30    2
40    3
50    4
dtype: int64

In [30]:
series.astype(float)

10    0.0
20    1.0
30    2.0
40    3.0
50    4.0
dtype: float64

In [31]:
series.astype(bool)

10    False
20     True
30     True
40     True
50     True
dtype: bool

In [32]:
## custom index
sale_series = [0,5,2,4,1]
items = ['coffee', 'tea', 'cola', 'soda', 'sugar']

sale_series_custom_index=pd.Series(sale_series, index=items, name='Sales')

In [33]:
sale_series_custom_index

coffee    0
tea       5
cola      2
soda      4
sugar     1
Name: Sales, dtype: int64

In [34]:
sale_series_custom_index.index.isin(['coffee', 'tea'])

array([ True,  True, False, False, False])

In [35]:
sale_series_custom_index['tea']

np.int64(5)

In [36]:
sale_series

[0, 5, 2, 4, 1]

In [37]:
sale_series_custom_index = pd.Series(sale_series, index=["Day 1", "Day 2", "Day 3", "Day 4", "Day 5"])

In [38]:
sale_series_custom_index

Day 1    0
Day 2    5
Day 3    2
Day 4    4
Day 5    1
dtype: int64

In [39]:
series

10    0
20    1
30    2
40    3
50    4
dtype: int64

In [40]:
series.sort_values()

10    0
20    1
30    2
40    3
50    4
dtype: int64

In [41]:
series.sort_values(ascending=False)

50    4
40    3
30    2
20    1
10    0
dtype: int64