In [1]:
import numpy as np

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [3]:
arr2 = np.array([5,4,3,2,1])
arr2.reshape
print(arr2)

[5 4 3 2 1]


In [6]:
arr3 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr3.shape)
print(arr3)

(2, 5)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [8]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape)  # Output: (2, 3)
print("Number of dimensions:", arr.ndim)  # Output: 2
print("Size (number of elements):", arr.size)  # Output: 6
print("Data type:", arr.dtype)  # Output: int32 (may vary based on platform)
print("Item size (in bytes):", arr.itemsize)  #

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [15]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

print("Addition: ", arr1+arr2)

print("Substraction: ", arr1-arr2)

print("Multiplication: ", arr1*arr2)

print("Division: ", arr1/arr2)

Addition:  [11 22 33 44 55]
Substraction:  [ -9 -18 -27 -36 -45]
Multiplication:  [ 10  40  90 160 250]
Division:  [0.1 0.1 0.1 0.1 0.1]


In [17]:
arr1=np.array([1,2,3,4,5])

print(np.sqrt(arr1))
print(np.exp(arr1))
print(np.sin(arr1))
print(np.log(arr1))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [46]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,13]])
print("Array: \n", arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 13]]


In [47]:
arr[1:, 2:]

array([[ 7,  8],
       [11, 13]])

In [48]:
arr[0:2,2:]

array([[3, 4],
       [7, 8]])

In [54]:
arr[1:, 1:3]

array([[ 6,  7],
       [10, 11]])

In [59]:
data = np.array([1,2,3,4,5,6,7])

mean = np.mean(data)
std_dev = np.std(data)

normalization_data = (data-mean) / std_dev
print("Normalized data: ", normalization_data)

Normalized data:  [-1.5 -1.  -0.5  0.   0.5  1.   1.5]


In [62]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

mean = np.mean(data)
print(mean)

median = np.median(data)
print(median)

std_dev = np.std(data)
print(std_dev)

variance = np.var(data)
print("Variance:", variance)

5.5
5.5
2.8722813232690143
Variance: 8.25


In [1]:
## iterating array
import numpy as np

arr = np.array([1,2,3,4])

for i in arr:
    print(i)

1
2
3
4


In [3]:
arr2=([[1,2,3],[4,5,6]])

for x in arr2:
    print(x)

for y in arr2:
    for z in y:
        print(z)

[1, 2, 3]
[4, 5, 6]
1
2
3
4
5
6


In [4]:
arr = ([[[1,2], [3,4], [5,6]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2==0)
print(x)

(array([1, 3, 5, 7]),)


In [12]:
from numpy import random

x = random.randint(100, size=(5))
print(x)

[52 74 99 98 24]


In [16]:
y = random.randint(100, size=(3,5))
print(y)

[[65 36 99  9 34]
 [75 61  1 99 10]
 [58 77 20 45 64]]


In [29]:
x_choice = random.choice([3,5,7,8], p=[0.0, 0.1, 0.6, 0.3], size=(100))
print(x_choice)

[8 8 7 7 5 7 8 7 7 8 7 7 7 7 8 7 7 8 7 7 7 8 5 8 7 8 8 7 7 7 7 8 8 7 7 7 7
 8 7 8 7 7 8 8 7 5 8 8 8 8 7 7 7 7 7 7 7 7 7 7 5 7 7 7 5 7 7 7 7 7 7 5 7 7
 8 8 8 5 8 7 7 7 7 7 7 5 8 8 7 7 5 7 8 8 7 7 5 5 8 8]


In [33]:
arr = np.array([1,2,3,4])
random.shuffle(arr)
print(arr)

[4 3 1 2]


In [34]:
x = random.normal(size=(2,3))
print(x)

[[-1.07749639  0.24026554 -0.45496453]
 [ 0.7102602  -0.78060196 -0.96838126]]


In [35]:
x = random.normal(loc=1, scale=2, size=(2,3))
print(x)

[[0.2944639  0.93597169 2.48799929]
 [2.60545561 2.71268723 3.06768197]]


In [37]:
## Exponential Distribution
x = random.exponential(scale=2, size=(2,3))
print(x)

[[0.39445088 2.73853345 1.49535985]
 [4.23358438 3.55009788 1.54293694]]


In [38]:
## Chi Square Distribution
x = random.chisquare(df=2, size=(2,3))
print(x)

[[0.69901078 0.65063431 0.24003125]
 [0.93536717 0.40720557 0.26669663]]


In [39]:
## Rayleigh Distribution
x = random.rayleigh(scale=2, size=(2,3))
print(x)

[[1.40850798 3.27078809 2.39454486]
 [1.66106546 2.12477971 4.95969662]]


In [40]:
x = random.pareto(a=2, size=(2,3))
print(x)

[[0.75993089 0.30342925 2.81362008]
 [1.29173713 1.09775033 1.30662475]]


In [41]:
x = random.zipf(a=2, size=(2, 3))
print(x)

[[6 1 1]
 [1 1 1]]


In [42]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.mod(arr1,arr2)
print(newarr)

[ 1  6  3  0  0 27]


In [43]:
arr = np.linspace(0,1,5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [46]:
arr = np.linspace(0,5,5)
print(arr)

[0.   1.25 2.5  3.75 5.  ]


In [45]:
arr = np.random.rand(10)
arr

array([0.61894279, 0.79373602, 0.62913069, 0.5969057 , 0.72559787,
       0.44078112, 0.64162347, 0.21857119, 0.07661059, 0.07473447])

In [56]:
arr = np.random.randint(10,100, size=(2,3))
arr

array([[28, 22, 13],
       [29, 96, 40]], dtype=int32)

In [60]:
arr = np.array([1,2,3,4,5,6])
reshape = arr.reshape(2,3)
arr
reshape

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
arr = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
arr

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])