In [1]:
import numpy as np

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [3]:
arr2 = np.array([5,4,3,2,1])
arr2.reshape
print(arr2)

[5 4 3 2 1]


In [6]:
arr3 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr3.shape)
print(arr3)

(2, 5)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [8]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape)  # Output: (2, 3)
print("Number of dimensions:", arr.ndim)  # Output: 2
print("Size (number of elements):", arr.size)  # Output: 6
print("Data type:", arr.dtype)  # Output: int32 (may vary based on platform)
print("Item size (in bytes):", arr.itemsize)  #

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [15]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

print("Addition: ", arr1+arr2)

print("Substraction: ", arr1-arr2)

print("Multiplication: ", arr1*arr2)

print("Division: ", arr1/arr2)

Addition:  [11 22 33 44 55]
Substraction:  [ -9 -18 -27 -36 -45]
Multiplication:  [ 10  40  90 160 250]
Division:  [0.1 0.1 0.1 0.1 0.1]


In [17]:
arr1=np.array([1,2,3,4,5])

print(np.sqrt(arr1))
print(np.exp(arr1))
print(np.sin(arr1))
print(np.log(arr1))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [46]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,13]])
print("Array: \n", arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 13]]


In [47]:
arr[1:, 2:]

array([[ 7,  8],
       [11, 13]])

In [48]:
arr[0:2,2:]

array([[3, 4],
       [7, 8]])

In [54]:
arr[1:, 1:3]

array([[ 6,  7],
       [10, 11]])

In [59]:
data = np.array([1,2,3,4,5,6,7])

mean = np.mean(data)
std_dev = np.std(data)

normalization_data = (data-mean) / std_dev
print("Normalized data: ", normalization_data)

Normalized data:  [-1.5 -1.  -0.5  0.   0.5  1.   1.5]


In [62]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

mean = np.mean(data)
print(mean)

median = np.median(data)
print(median)

std_dev = np.std(data)
print(std_dev)

variance = np.var(data)
print("Variance:", variance)

5.5
5.5
2.8722813232690143
Variance: 8.25


In [1]:
## iterating array
import numpy as np

arr = np.array([1,2,3,4])

for i in arr:
    print(i)

1
2
3
4


In [3]:
arr2=([[1,2,3],[4,5,6]])

for x in arr2:
    print(x)

for y in arr2:
    for z in y:
        print(z)

[1, 2, 3]
[4, 5, 6]
1
2
3
4
5
6


In [4]:
arr = ([[[1,2], [3,4], [5,6]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2==0)
print(x)

(array([1, 3, 5, 7]),)
